class GarmentOverlay {
  constructor(canvas, options = {}) { this.canvas = canvas; this.ctx = canvas.getContext('2d'); this.garmentType = options.garmentType || 'hoodie'; this.motion = .55; this.brightness = .65; this.pose = null; this.x = canvas.width / 2; this.y = canvas.height * .58; this.scale = 1; this.palette = { hoodie:'#7c3aed', shirt:'#f97316', dress:'#ec4899', jacket:'#22c55e' }; this.attachEvents(); }
  setType(type) { this.garmentType = type; }
  setMotion(value) { this.motion = Number(value) / 100; }
  setBrightness(value) { this.brightness = Number(value) / 100; }
  setPose(landmarks) { this.pose = landmarks; }
  syncCanvasSize() { const r = this.canvas.getBoundingClientRect(); this.canvas.width = Math.max(1, Math.round(r.width * devicePixelRatio)); this.canvas.height = Math.max(1, Math.round(r.height * devicePixelRatio)); }
  attachEvents() { let start; this.canvas.addEventListener('pointerdown', e => { const r=this.canvas.getBoundingClientRect(); start={x:e.clientX-r.left,y:e.clientY-r.top,ox:this.x,oy:this.y}; this.canvas.setPointerCapture(e.pointerId); }); this.canvas.addEventListener('pointermove', e => { if(!start)return; const r=this.canvas.getBoundingClientRect(); this.x=start.ox+(e.clientX-r.left-start.x)*devicePixelRatio; this.y=start.oy+(e.clientY-r.top-start.y)*devicePixelRatio; }); this.canvas.addEventListener('pointerup', () => { start=null; }); }
  render(time) { const ctx=this.ctx,w=this.canvas.width,h=this.canvas.height; ctx.clearRect(0,0,w,h); let x=this.x,y=this.y,s=this.scale; const lm=this.pose || []; const l=lm[11], r=lm[12], lh=lm[23], rh=lm[24]; if(l&&r){x=((l.x+r.x)/2)*w;y=((l.y+r.y)/2)*h+70*s;const shoulder=Math.abs(l.x-r.x)*w;s=Math.max(.5,shoulder/180); if(lh&&rh){const hip=Math.abs(lh.x-rh.x)*w;s=Math.max(s,hip/150);}} const bw=180*s,bh=240*s; const bob=Math.sin(time/240)*this.motion*12; ctx.save();ctx.translate(x,y+bob);ctx.filter=`brightness(${.6+this.brightness})`;ctx.fillStyle=this.palette[this.garmentType]||'#7c3aed';ctx.beginPath();ctx.moveTo(-bw*.35,-bh*.45);ctx.lineTo(-bw*.75,-bh*.2);ctx.lineTo(-bw*.5,bh*.4);ctx.lineTo(-bw*.18,bh*.3);ctx.lineTo(-bw*.15,bh*.5);ctx.lineTo(bw*.15,bh*.5);ctx.lineTo(bw*.18,bh*.3);ctx.lineTo(bw*.5,bh*.4);ctx.lineTo(bw*.75,-bh*.2);ctx.lineTo(bw*.35,-bh*.45);ctx.closePath();ctx.fill();ctx.restore(); }
}
window.GarmentOverlay = GarmentOverlay;
